export const ALLOWED_DSPS = [
  "iTunes / Apple Music + Shazam",
  "Deezer",
  "Spotify",
  "YouTube Music",
  "Tidal",
  "Amazon",
  "AMI Entertainment",
  "Qobuz",
  "Pandora",
  "KKBOX",
  "7Digital + Snapchat",
  "iMusica",
  "Soundcloud",
  "iHeartRadio",
  "Anghami",
  "SoundExchange",
  "JioSaavn",
  "AWA",
  "NetEase",
  "Sirius XM",
  "YouTube Content ID",
  "Facebook Audio Library",
  "Facebook Rights Manager",
  "Mixcloud",
  "TikTok",
  "Boomplay",
  "Peloton",
  "Audiomack",
  "Gaana",
  "Kuack",
  "Kuaishou",
  "Audible Magic",
  "Tuned Global / Line Music",
  "Lissen",
];

export const ALLOWED_CHANNELS = [
  "Subscription Streaming",
  "Ad-Supported Streaming",
  "UGC Licensing",
  "UGC Consumption",
  "UGC Ad Revenue Share",
  "Claimed UGC",
  "Download",
  "Other",
];
